on: [push, pull_request]

jobs:
  armv7_job:
    # The host should always be Linux
    runs-on: ubuntu-24.04
    name: Build on archlinux aarch64
    steps:
      - uses: actions/checkout@v4
      - uses: uraimo/run-on-arch-action@v3
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: archarm_latest

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}

          # Set an output parameter `uname` for use in subsequent steps
          run: |
            echo "$(cat /etc/os-release)"
          # git clone -b 1.26.4 https://gitlab.freedesktop.org/gstreamer/gstreamer.git
