on: [push, pull_request]

jobs:
  arm64_job:
    # The host should always be Linux
    runs-on: ubuntu-24.04
    name: Build on archlinux aarch64
    steps:
      - uses: actions/checkout@v4
      - uses: uraimo/run-on-arch-action@v3
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu24.04

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}

          # Set an output parameter `uname` for use in subsequent steps
          run: |
          	    apt update -y
																	yes | apt upgrade
																	apt install meson -y
 																git clon https://gitlab.freedesktop.org/gstreamer/gstreamer.git gstreamer
																	cd gstreamer
																	meson setup -Dgst-full-target-type=static_library --default-library=static -Dintrospection=enabled -Dgst-full-libraries=app,video,player  -Dbase=enabled -Dgood=enabled -Dbad=enabled -Dlibav=enabled  -Dtests=disabled -Dexamples=disabled -Dgstreamer:check=disabled -Dgstreamer:benchmarks=disabled -Dgstreamer:libunwind=disabled -Dgstreamer:libdw=disabled -Dgst-plugins-good:cairo=disabled -Dgst-plugins-good:examples=disabled -Dgst-plugins-good:gdk-pixbuf=disabled -Dgst-plugins-good:oss=disabled -Dgst-plugins-good:oss4=disabled -Dgst-plugins-good:v4l2=disabled -Dgst-plugins-good:aalib=disabled -Dgst-plugins-base:examples=disabled -Dgst-plugins-base:pango=disabled -Dgst-plugins-bad:androidmedia=disabled -Dgst-plugins-bad:rtmp=disabled -Dgst-plugins-bad:shm=disabled -Dgst-plugins-bad:zbar=disabled -Dgst-plugins-bad:webp=disabled -Dgst-plugins-bad:hls-crypto=openssl --wrap-mode=nodownload builddir --prefix=/root/gst/
																	
